/** Shared input placeholders across student and staff portals. */
export const formPlaceholders = {
  studentId: "0123-4567",
  email: "you@school.edu",
  password: "At least 8 characters",
  confirmPassword: "Re-enter your password",
  firstName: "Juan",
  middleName: "T.",
  lastName: "Tamad",
  nameExtension: "Jr.",
  program: "BS Information Technology",
  section: "A",
  department: "e.g. College of Computing",
  organizationName: "e.g. Computer Society",
  eventTitle: "e.g. Tech Summit 2026",
  eventDescription: "Brief event description",
  venueName: "e.g. Main Auditorium",
  notificationTitle: "Announcement title",
  notificationBody: "Message to all recipients",
  staffEmail: "staff@school.edu",
  verificationCode: "000000",
  feedback: "Share your experience…",
  searchStudent: "Search by name or ID",
} as const;
